// console.log(double(4));
export const InitalMovies = [
  {
    poster: "https://wallpapercave.com/dwp2x/tq3jwQg.jpg",
    trailer:"https://www.youtube.com/embed/2TAOizOnNPo",
    name: "The fast and The furious",
    Summary: "Los Angeles police officer Brian O'Conner must decide where his loyalty really lies when he becomes enamored with the street racing world he has been sent undercover to destroy.",
    Rating: "⭐⭐⭐⭐",
    Rate: 4,
    Year: 2001,
  },
  {
    poster: "https://wallpapercave.com/dwp2x/yN6gKa5.jpg",
    trailer:"https://www.youtube.com/embed/F_VIM03DXWI",
    name: "2 Fast & 2 Furious",
    Summary: "Former cop Brian O'Conner is called upon to bust a dangerous criminal and he recruits the help of a former childhood friend and street racer who has a chance to redeem himself.",
    Rating: "⭐⭐⭐⭐⭐",
    Rate: 5,
    Year: 2003,
  },
  {
    poster: "https://wallpapercave.com/wp/wp1825855.jpg",
    trailer:"https://www.youtube.com/embed/p8HQ2JLlc4E",
    name: "The Fast and the Furious: Tokyo Drift",
    Summary: "A teenager becomes a major competitor in the world of drift racing after moving in with his father in Tokyo to avoid a jail sentence in America.",
    Rating: "⭐⭐⭐⭐",
    Rate: 4,
    Year: 2006,
  },
  {
    poster: "https://wallpapercave.com/dwp2x/ok4EoNj.jpg",
    trailer:"https://www.youtube.com/embed/9eBR_u2iRus",
    name: "The Fast & Furious 4",
    Summary: "Brian O'Conner, back working for the FBI in Los Angeles, teams up with Dominic Toretto to bring down a heroin importer by infiltrating his operation.",
    Rating: "⭐⭐⭐",
    Year: 2009,
  },
  {
    poster: "https://wallpapercave.com/wp/wp1983461.jpg",
    trailer:"https://www.youtube.com/embed/mw2AqdB5EVA",
    name: "Fast Five",
    Summary: "Dominic Toretto and his crew of street racers plan a massive heist to buy their freedom while in the sights of a powerful Brazilian drug lord and a dangerous federal agent.",
    Rating: "⭐⭐⭐⭐⭐",
    Rate: 5,
    Year: 2011,
  },
  {
    poster: "https://wallpapercave.com/dwp2x/wp9832983.jpg",
    trailer: "https://www.youtube.com/embed/dKi5XoeTN0k",
    name: "Fast & Furious 6",
    Summary: "Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets sidetracked with facing his presumed deceased girlfriend, Letty.",
    Rating: "⭐⭐⭐⭐",
    Rate: 4,
    Year: 2013,
  },
  {
    poster: "https://wallpapercave.com/dwp2x/wp1830970.jpg",
    trailer:"https://www.youtube.com/embed/yISKeT6sDOg",
    name: "Furious 7",
    Summary: "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
    Rating: "⭐⭐⭐⭐",
    Rate: 4,
    Year: 2015,
  },
  {
    poster: "https://wallpapercave.com/dwp2x/wp8243875.jpg",
    trailer:"https://www.youtube.com/embed/H0tiy4konIg",
    name: "fast and furious 8",
    Summary: "In the film, Dominic Toretto has settled down with his wife Letty Ortiz, until cyberterrorist Cipher coerces him into working for her and turns him against his team, forcing them to find Dom and take down Cipher.",
    Rating: "⭐⭐⭐⭐⭐",
    Rate: 5,
    Year: 2017,
  },
  {
    poster: "https://i.ytimg.com/vi/fEE4RO-_jug/maxresdefault.jpg",
    trailer:"https://www.youtube.com/embed/FqAjVAf5fNA",
    name: "F9",
    Summary: "Dom and the crew must take on an international terrorist who turns out to be Dom and Mia's estranged brother.",
    Rating: "⭐⭐⭐⭐",
    Rate: 4,
    Year: 2021,
  },
];
